### ISSUE TITLE
Auto suggest misses 'else'

### ISSUE THREAD

**Issue by Blargian** [ytliu74/obsidian-pseudocode#14]
Hi, 

I came across your plugin for Obsidian this morning. Firstly, thank you! This is an amazing plugin and so useful. 

Quite possible I'm doing something wrong but I noticed that the autosuggest seems to be missing the 'else' directive. It finds 'elif{}' when i start typing 'el', but not '\else'. I attached a screenshot of what I mean below:  

![image](https://github.com/ytliu74/obsidian-pseudocode/assets/41984034/7ab25ed1-0f05-435b-8b74-2f176f9d16d5)

I am using version 1.5.3 of the plugin and obsidian version 1.4.16 on Windows 11.

**Comment by ytliu74** [comment]
Oh, I am so sorry. I somehow omitted the `\Else`. I've updated the code but the CI does not work well. So the new release might be a little late.

**Comment by ytliu74** [comment]
This issue is solved at the [latest release](https://github.com/ytliu74/obsidian-pseudocode/releases/tag/1.5.4). Thanks!
