### ISSUE TITLE
Support for ForEach and break

### ISSUE THREAD

**Issue by rosshjb** [ytliu74/obsidian-pseudocode#15]
Could you support`ForEach`, `break` and `continue` command?

**Comment by rosshjb** [comment]
Is there option to do not display `end if`, `end for` and `end while`...?

**Comment by ytliu74** [comment]
1. Hi, the `\Break` and `\Continue` now can be correctly shown in auto-completion. But I need to look into the the source code of pseudocode.js to help support `Foreach`
2. In the plugin settings, you can toggle the "No End" option to control whether to show 'end'.

**Comment by rosshjb** [comment]
It seems that `ForEach` can be used as `\in` as a workaround.

```
\For{$e \in A$}
    \State{iterate A}
\EndFor
```

![image](https://github.com/ytliu74/obsidian-pseudocode/assets/77195477/4138d0e1-edb2-4638-b73e-2783b3c16516)

**Comment by ytliu74** [comment]
This could indeed be a workaround. The original pseudocode.js also supports `Forall`, which might be an alternative to `Foreach`.

**Comment by ytliu74** [comment]
Hi, `ForAll` is actually supported. And I believe it can be serve as the same meaning of ForEach. And `ForAll` is also included into the auto-complete now.
