### ISSUE TITLE
Adjust alignment for comments

### ISSUE THREAD

**Issue by rosshjb** [ytliu74/obsidian-pseudocode#16]
Could you support an option to align comments?

Sample:
![image](https://github.com/ytliu74/obsidian-pseudocode/assets/77195477/fd050a9e-bd75-4609-93e2-137b7828cf77)

```
\begin{algorithm}
	\caption{Merge Sort}
	\begin{algorithmic}
	    \Procedure{Merge-Sort}{$A,p,q,r$}
			\If{$p\ge r$} \Comment{zero or one element?}
				\State \Return\Comment{early return}
			\EndIf
			\State $q \gets \lfloor(p+r)/2\rfloor$
			\State \Call{Merge-Sort}{$A,p,q$}
			\State \Call{Merge-Sort}{$A,q+1,r$}
			\State \Call{Merge}{$A,p,q,r$}
	    \EndProcedure
	\end{algorithmic}
\end{algorithm}
```

**Comment by ytliu74** [comment]
Hi, well, the comment now indeed looks bad. How about let them align to the right side like below:
<img width="382" alt="image" src="https://github.com/ytliu74/obsidian-pseudocode/assets/58876108/be88f97d-497b-4f15-b774-05df24f8ca48">
If you are okay with this, I can try to implement.

**Comment by rosshjb** [comment]
@ytliu74 
Awesome!
If the comment is on a separate line, it would be better to display it as before.

**Comment by ytliu74** [comment]
Hi @rosshjb, you can refer to this pull request https://github.com/ytliu74/obsidian-pseudocode/pull/18 for a possible solution. But it's not perfect. But you can use it as a workaround, thanks.

**Comment by dzx-dzx** [comment]
Example here:
![image](https://github.com/ytliu74/obsidian-pseudocode/assets/31068367/c944ef93-a9be-4c28-b4f0-1a5d9e35ac65)
![image](https://github.com/ytliu74/obsidian-pseudocode/assets/31068367/b009de50-223b-41c1-b7ca-814e469227c8)
![image](https://github.com/ytliu74/obsidian-pseudocode/assets/31068367/8a8085b9-92da-4ce6-90ad-e64c5a68c6a1)

**Comment by anton-dergunov** [comment]
> Hi @rosshjb, you can refer to this pull request #18 for a possible solution. But it's not perfect. But you can use it as a workaround, thanks.

This change seem to break the layout...
![image](https://github.com/user-attachments/assets/4008c7bd-67da-4bc0-b7de-d4c2f145a203)

**Comment by anton-dergunov** [comment]
This fix worked for me

```
.ps-comment {
        float: right;
}
```

![image](https://github.com/user-attachments/assets/c8fa8fc7-74c9-4fc3-bc7f-a185382d4149)

**Comment by anton-dergunov** [comment]
Or, to make it even more consistent with LaTeX package documentation (https://ctan.math.washington.edu/tex-archive/macros/latex/contrib/algpseudocodex/algpseudocodex.pdf):

![image](https://github.com/user-attachments/assets/2017ace4-31e1-429b-aea6-84b0f92d659b)

Change it like that:

```
.ps-root {
        font-family: KaTeX_Main, "Times New Roman", Times, serif;
        font-weight: 400;
        font-variant: normal;
        font-style: normal;
        text-transform: none;
}

.ps-comment {
        font-family: KaTeX_Main, "Times New Roman", Times, serif;
        font-weight: 400;
        font-variant: normal;
        font-style: italic;
        text-transform: none;
        opacity: 70%;
        float: right;
}
```

Now it looks like this:

![image](https://github.com/user-attachments/assets/46f1b947-4eba-48e7-a8c4-fc0ad6ada029)

I just hacked this file: ~/.obsidian/plugins/pseudocode-in-obs/styles.css

**Comment by anton-dergunov** [comment]
https://github.com/ytliu74/obsidian-pseudocode/pull/22
This could address the issue, but more clean up is possible.

**Comment by ytliu74** [comment]
Thanks so much for the support from @anton-dergunov. I've already merged the commit and it's included in the newest version.
