### ISSUE TITLE
Add end tags after writing start tags

### ISSUE THREAD

**Issue by elkalt** [ytliu74/obsidian-pseudocode#17]
It would be nice if when writing/autocompleting an tag (ie. \For{}) the corresponding end tag also gets added on the next line (ie. \EndFor).

**Comment by ytliu74** [comment]
Yeah, this sounds like a good idea. Will be working on it this weekend. Thanks for the suggestion.

**Comment by ytliu74** [comment]
Please check the lastest [update](https://github.com/ytliu74/obsidian-pseudocode/releases/tag/1.5.6).
