### ISSUE TITLE
[Feature Request] Support Dark Theme

### ISSUE THREAD

**Issue by TroySigX** [ytliu74/obsidian-pseudocode#19]
As of now, `pseudocode` only displays white background with black text. Can we achieve dark background with light text when using dark mode?

**Comment by ytliu74** [comment]
This is a good suggestion and I am working on it. Thanks.

**Comment by ytliu74** [comment]
I've added a `Follow System Theme` feature, accessible in the settings tab. It adjusts the pseudocode block color to match your Obsidian theme, whether light or dark. Please try it out and report any issues. Thanks.
