### ISSUE TITLE
Extend KaTeX with custom commands

### ISSUE THREAD

**Issue by mzietlow** [ytliu74/obsidian-pseudocode#2]
Thank you for the great work! I just started using your plugin and so far everything works extremely well.

Just wondering: I am also using the Extended MathJax plugin that allows me to inject custom commands using a preamble.sty file.
For example:

```latex
\DeclarePairedDelimiter{\floor}{\lfloor}{\rfloor}
\DeclarePairedDelimiter{\ceil}{\lceil}{\rceil}
...

% Linear Algebra
\newcommand{\transpose}[1]{ {#1}^{\intercal} }
...
```

Would it be possible for your plugin to also read the preamble.sty file and load the same custom commands?

Best wishes
~

**Comment by mzietlow** [comment]
Ohhh, don't worry! Take your time, I really appreciate your efforts, there is no need to rush. 10 days is nothing you would have to apologize for 🙏 

I'm just glad that you're going to take a look at it and looking forward to an eventual implementation 💪

**Comment by ytliu74** [comment]
After reviewing the KaTeX document, I found that they only support a limited number of [macros](https://katex.org/docs/supported.html#macros). Unfortunately, `\DeclarePairedDelimiter`, which you mentioned earlier, is not directly supported by KaTeX. However, it can be rewritten using `\newcommand`. Additionally, I am planning to implement a pre-processing step for unsupported functions and convert them into a format that is supported by KaTeX. 
Initially, I will focus on implementing the easier version that supports only [these macros](https://katex.org/docs/supported.html#macros).
Sorry for being a little low-productive. I am working on my graduation thesis lately..

**Comment by ytliu74** [comment]
A basic version is done at [release 1.2.0](https://github.com/ytliu74/obsidian-pseudocode/releases/tag/1.2.0). If you encounter any bug, please let me know.

**Comment by mzietlow** [comment]
Repeating myself here, but you really shouldn't apologize. Plus, I wouldn't exactly define thesis work as low-productive.

Working good so far, rather unfortunate that KaTeX doesn't provide an implementation of `\DeclarePairedDelimiter` or `\DeclareMathOperator`. 

I have defined my own `\DeclareMathOperator` as 

```latex
\newcommand{\DeclareMathOperator}[2]{%
  \newcommand{#1}{\operatorname{#2}}%
}
```

which is inferior, but works for the majority of my uses. For `\DeclarePairedDelimiter` I haven't come up with an alternative definition yet.

**Comment by mzietlow** [comment]
Oh no, didn't intend to close the issue, sorry

**Comment by ytliu74** [comment]
How about these:
```latex
%\DeclarePairedDelimiter{\floor}{\lfloor}{\rfloor}
%\DeclarePairedDelimiter{\ceil}{\lceil}{\rceil}

\newcommand{\flooor}[1]{\left\lfloor#1\right\rfloor}
\newcommand{\ceeeil}[1]{\left\lceil#1\right\rceil}
```
It seems to work fine. And if there's no bug, I will try to implement some auto-translation so we can support more macros.

**Comment by mzietlow** [comment]
Ah, yes, I have a couple of those and rewriting them all seems a little tedious, an optional auto-translation would be fantastic 🎉

**Comment by ytliu74** [comment]
Can you share all the additional macros you need? And some test cases would be better.

**Comment by mzietlow** [comment]
Sure, I am using `\newcommand`, `\DeclarePairedDelimiter`, `\DeclareMathOperator`, and `\DeclareMathOperator*`.
My current preamble.sty looks as follows:

```latex
% Beträge und Misc
\DeclarePairedDelimiter{\abs}{\lvert}{\rvert}%
\DeclarePairedDelimiter{\norm}{\lVert}{\rVert}%
\DeclarePairedDelimiter{\euclidnorm}{\lVert}{\rVert_{2}}%
\DeclarePairedDelimiter{\sumnorm}{\lVert}{\rVert_{1}}%
\DeclarePairedDelimiter{\maxnorm}{\lVert}{\rVert_{\infty}}%
\DeclarePairedDelimiter{\ang}{\langle}{\rangle}%

% Divides
\newcommand{\divides}[0]{\vert}
\newcommand{\ndivides}[0]{\not\hspace{0pt}\vert\ }

% Argmax
\DeclareMathOperator*{\argmax}{arg\,max}
\DeclareMathOperator*{\argmin}{arg\,min}

% Floor and Ceil
\DeclarePairedDelimiter{\floor}{\lfloor}{\rfloor}%
\DeclarePairedDelimiter{\ceil}{\lceil}{\rceil}%

% Graphentheorie
\DeclareMathOperator{\dist}{dist}
\DeclareMathOperator{\ex}{ex}

% Lineare Algebra
\newcommand{\transpose}[1]{ #1^{\top} }
\DeclareMathOperator{\cond}{cond}
\DeclareMathOperator{\Rg}{Rg}
\DeclareMathOperator{\spur}{Spur}
\DeclareMathOperator{\cof}{Cof}
\DeclareMathOperator{\adj}{Adj}
\newcommand{\bigzero}[0]{\huge0}

%% Darstellungsmatrix
\newcommand{\dmat}[3]{ \prescript{}{\mathcal{#1}}{#2}_{\mathcal{#3}}}

% Analysis
\DeclareMathOperator{\id}{id}
\DeclareMathOperator{\grad}{Grad}

% Numerik
\DeclareMathOperator{\rd}{rd}

%% Maschinenoperationen
\newcommand{\mplus}[0]{\oplus}
\newcommand{\mminus}[0]{\ominus}
\newcommand{\mtimes}[0]{\otimes}
\newcommand{\mdiv}[0]{\oslash}

% Zahlentheorie
\DeclareMathOperator{\ggt}{ggT}
\DeclareMathOperator{\kgv}{kgV}
```

**Comment by ytliu74** [comment]
Got it. Thanks.

**Comment by ytliu74** [comment]
In the latest update, I added a translator that supports `\DeclarePairedDelimiter`, `\DeclareMathOperator*`, and `\DeclareMathOperator`. However, it may not be fully supported yet. Please try it out and let me know if you encounter any issues. If necessary, you can check the translated macros in the console.

**Comment by mzietlow** [comment]
Looking good, no issues so far. Thank you for your efforts! 🙏

**Comment by ytliu74** [comment]
Thanks, it's great to hear that everything is working fine. I am gonna close this issue. If you have further bug report, you can start a new issue or just reply here.
