### ISSUE TITLE
Add Repeat-Until as pair suggestion

### ISSUE THREAD

**Issue by NathanBHay** [ytliu74/obsidian-pseudocode#20]
`\Repeat` and `\Until{}` should be a valid pair suggestion as shown in section 3.1.3 of the [algorithmicx docs](https://tug.ctan.org/macros/latex/contrib/algorithmicx/algorithmicx.pdf).

**Comment by ytliu74** [comment]
Thank you for your feedback. The latest version includes your suggestions. You can also refer to all supported pair suggestions here: https://github.com/ytliu74/obsidian-pseudocode/blob/98281887241f55c4c5f8704ddd6ea85205ab0b71/src/auto_complete.ts#L103
