### ISSUE TITLE
\begin{algorithmic}[1] not working

### ISSUE THREAD

**Issue by mii-key** [ytliu74/obsidian-pseudocode#21]
Hi, @ytliu74 

First off, I want to say a huge thanks for creating and maintaining the plugin. I truly appreciate all the effort you've put into it.

I've come across a small hiccup with the `\begin{algorithmic}[1]` command not working as intended. I noticed there's an option to enable line numbers globally, but it would be super helpful to have the ability to toggle line numbers on a per-algorithm basis with `\begin{algorithmic}[1]`.

STR:
using `\begin{algorithmic}[1]` instead of `\begin{algorithmic}` in the example from your docs produce:

![Obsidian_l5gHCYHPSY](https://github.com/ytliu74/obsidian-pseudocode/assets/130221089/0d41dda0-3f36-45ee-9d73-cbb4269ee0cd)
Windows 11x64, Obsidian 1.6.3, Pseudocode 1.6.0

Would it be possible to consider adding support for this in a future update? It would offer a great deal of flexibility for those of us who need to customize our documentation further.

Thanks again for your awesome work on this plugin.

**Comment by ytliu74** [comment]
Hi mii-key, I appreciate your support for this plugin. 

The feature you're referring to is associated with [pseudocode.js](https://github.com/SaswatPadhi/pseudocode.js), which renders the pseudocode. Unfortunately, I can't assist directly with this. However, you could open an issue on pseudocode.js and once they update it with the new feature, I'll merge it into my version of pseudocode.js.
