### ISSUE TITLE
How to change background color？

### ISSUE THREAD

**Issue by yuner2001** [ytliu74/obsidian-pseudocode#23]
@ytliu74  Thank u for the great work for obsidian🥰, it works well in the light mode, but when I change my ob to the dark mode, the background pseudo code block  is still black after rendering, Should I need to modify the source code for this or there are some setting which i can change?

**Comment by ytliu74** [comment]
Hi! Thanks for your support!

So you issue is: The pseudocode block follows the theme change (light -> dark)? So what you want is to keep pseudocode white background with black characters? If so, you can simply turn off the `Follow System Theme` in the plugin setting page.

Actually this is an extra feature supported. The related feature request issue is here: https://github.com/ytliu74/obsidian-pseudocode/issues/19

Hope this helps!

**Comment by yuner2001** [comment]
> Hi! Thanks for your support!
> 
> 
> 
> So you issue is: The pseudocode block follows the theme change (light -> dark)? So what you want is to keep pseudocode white background with black characters? If so, you can simply turn off the `Follow System Theme` in the plugin setting page.
> 
> 
> 
> Actually this is an extra feature supported. The related feature request issue is here: https://github.com/ytliu74/obsidian-pseudocode/issues/19
> 
> 
> 
> Hope this helps!

Thx a lot! I will try it.

**Comment by ytliu74** [comment]
Just checking out whether your issue is solved.
