### ISSUE TITLE
Every time I reopen obsidian, the load file sign is displayed

### ISSUE THREAD

**Issue by SnakeHit** [ytliu74/obsidian-pseudocode#3]
<img width="317" alt="image" src="https://github.com/ytliu74/obsidian-pseudocode/assets/45898625/250d1d50-e4b3-4771-beb7-6844f2c4e7b8">

**Comment by ytliu74** [comment]
Well. I just think this might be a useful message. I will add a setting to toggle this sign (or notice) soon.

**Comment by SnakeHit** [comment]
> Well. I just think this might be a useful message. I will add a setting to toggle this sign (or notice) soon.

Thanks for your reply. Have a nice day.

**Comment by ytliu74** [comment]
I have just released an update that includes a toggle for this feature. By default, it is set to "false". Thank you for your feedback.
