### ISSUE TITLE
Reading Mode?

### ISSUE THREAD

**Issue by mayurankv** [ytliu74/obsidian-pseudocode#4]
This works amazingly in live preview mode. Would it be possible to get this working in the reading mode as well?

**Comment by ytliu74** [comment]
Sorry, but what platform and version (both Obsidian & the plugin) are you at? The plugin works fine in my machine in both live-preview and reading. You can try to update the plugin to the latest version.

**Comment by mayurankv** [comment]
Hmm, that's weird. I have zero idea what changed but originally it was rendering as a codeblock in preview mode. I tried it this morning and its working as expected! Don't think I updated anything but I'm not complaining haha. Thank you so much!

**Comment by ytliu74** [comment]
🤔
