### ISSUE TITLE
the row number does NOT render

### ISSUE THREAD

**Issue by sti1l-0** [ytliu74/obsidian-pseudocode#6]
the rendered pseudocode in your example be like:

![example](https://github.com/ytliu74/obsidian-pseudocode/assets/37724877/d9e5d674-b1a9-40a6-af42-01eb59660933)

in my local obsidian:

![mine](https://github.com/ytliu74/obsidian-pseudocode/assets/37724877/f66d1a3d-8fa9-45a3-9b7f-0ff7797b391a)

so the row number was not rendered.

**Comment by ytliu74** [comment]
There is a setting for this. You can toggle it in your setting page for "Pseudocode" here.
![image](https://github.com/ytliu74/obsidian-pseudocode/assets/58876108/f8aa1c3d-473c-47ab-82a6-ea980f4383ac)
