### ISSUE TITLE
Can't get lines for my algorithm

### ISSUE THREAD

**Issue by XgamerTV** [ytliu74/obsidian-pseudocode#7]
Hi,
When copy pasting over an example code I don't get any line numbers on my export and \begin{algorithmic}[1] doesn't seem to work.
Would be great to get code lines and it seemed to be the case in the pictures.

Other then that good plugin!

**Comment by ytliu74** [comment]
Ok, if you mean no line number inside Obsidian, please refer to issue #6. You need to toggle the `Show Line Number`.
But if you mean the code export, this is indeed a missing feature. Export now does not consider additional settings, e.g. line number. I will try to implement this feature ASAP.

**Comment by ytliu74** [comment]
I just test with export LaTeX code. Using `\begin{algorithmic}[1]` could render line number for me. I am just using `xelatex code.tex`, where `code.tex` is the export code. If the issue persists, could you share your LaTeX code?

**Comment by ytliu74** [comment]
Please try the latest version. I've already add relevant support for this. If you encounter any other related issues, please feel free to share them here.

**Comment by XgamerTV** [comment]
Everything works now! (I didn't have the option on and I needed it for PDF export) Thx for the quick help. 

One more question: Is there any way to disable the underlines and change the words for ending if,for,while statements (Probably not cause its latex default right?)

**Comment by ytliu74** [comment]
I'm sorry, I don't fully understand. What does "disable the underlines" mean?

Additionally, you can only choose whether or not to display the end statement by toggling the "No End" option in the settings page.

**Comment by XgamerTV** [comment]
Ah ok that's what I thought...I meant the lines around the title because I don't really like them but its latex so yeah thx for the info though :)

**Comment by ytliu74** [comment]
Well, even though it could be implemented, but would be not consistent with LaTeX.

And I am gonna close this issue. If you have any further problems or feature suggestions, please feel free to share them.
